### ISSUE TITLE
Predix CLI is not installed in Windows batch file

### ISSUE THREAD

**Issue by Tomoharu-Kanayama** [PredixDev/local-setup#13]
Hi,  

setup-windows.bat is used in the following command of the tutorial.
When executing the following command, the error "bash: px: command not found" occurred.
Because Predix CLI is not installed in Windows batch file (setup-windows.bat).
Please check "exit / b 0" on line 216 of this file.

https://github.com/PredixDev/local-setup/commit/eeb8f13b370343b281d1ac900551f2ec0a9ab11f

@powershell -Command "(new-object net.webclient).DownloadFile('https://raw.githubusercontent.com/PredixDev/predix-machine-template-adapter-simulator/master/scripts/quickstart-machine-w-simulator.bat','quickstart-machine-w-simulator.bat')" && "quickstart-machine-w-simulator.bat"

Tutrial : https://www.predix.io/resources/tutorials/tutorial-details.html?tutorial_id=2053&tag=2054&journey=Setup%20Laptop%2FDevbox%20for%20Predix&resources=1785,2053,1743

**Comment by turnerth** [comment]
See this line?

https://github.com/PredixDev/predix-machine-template-adapter-simulator/blob/master/scripts/quickstart-machine-w-simulator.bat#L43

It does have the /predixcli

There are not 216 lines in that file.  Let me check the setup-windows.bat file next, maybe you mean that.

**Comment by turnerth** [comment]
So, yes, I do see that on line 216 of setup-windows.bat.  I don't have a windows box with me right now.  Did you try without that and it worked correctly?  

Have any thoughts as to why the developer had that in there on that line?

I'll go ahead and take it out.

**Comment by Tomoharu-Kanayama** [comment]
@turnerth 
Thanks!
I tried without that, It worked well in the Windows 7 environment.
