### ISSUE TITLE
Unable to find artifact: winddata-timeseries-service:jar:2.0.35

### ISSUE THREAD

**Issue by robbannn** [PredixDev/local-setup#15]
Im following the tutorial "[Edge Starter: Add Predix Machine on an Personal Laptop/DevBox](https://www.predix.io/resources/tutorials/tutorial-details.html?tutorial_id=2053&tag=2054&journey=Setup%20Laptop%2FDevbox%20for%20Predix&resources=1785,2053,1743)".

I run the command:

`@powershell -Command "(new-object net.webclient).DownloadFile('https://raw.githubusercontent.com/PredixDev/predix-machine-template-adapter-simulator/master/scripts/quickstart-machine-w-simulator.bat','quickstart-machine-w-simulator.bat')" && "quickstart-machine-w-simulator.bat"`

which sets up UAA, Asset-service,  Time-series-service and "hello-world"-app (which by the way doesn't contain any login link as stated in the tutorial, only 2 links).

Anyhow, the command sets all these things up, but it ends with an error:

`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.10:copy (default-cli) on project winddata-timeseries-service: Unable to find artifact.: Failure to find com.ge.predix.solsvc:winddata-timeseries-service:jar:2.0.35 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
`
My settings.xml contains:

`<server>`
`    <id>predix.repo</id>`
`    <username>robin.nilsson85@gmail.com</username>`
`    <password>**my password**</password>`
`</server>`

Im not behind a proxy.

Ive made sure I can go to artifactory.predix.io, login and can see that .jar and deleting `~/.m2/repository/com/ge/predix/solsvc` and retry.

How can I overcome this issue?

**Comment by turnerth** [comment]
please see forum.predix.io for answer.
