### ISSUE TITLE
Brew Formula Name Changed

### ISSUE THREAD

**Issue by kaytea** [PredixDev/local-setup#18]
I believe the VMWare formula name has changed ( from `vmware` to `vmware-fusion`)

This is part of the output from running `bash <( curl https://raw.githubusercontent.com/PredixDev/local-setup/master/setup-mac.sh ) --vmware` 
![image](https://user-images.githubusercontent.com/8615780/41995318-1ef05ebe-7a06-11e8-8bce-8b51fba62766.png)

Manual execution of the command `brew cask install vmware` also fails (`brew cask install vmware-fusion` worked though!)

https://github.com/PredixDev/local-setup/blob/5230bdcaf4a31a8d53dd17f5f2c3d5bbc6c92154/setup-mac.sh#L179

**Comment by turnerth** [comment]
good catch, this will go out with next release
