### ISSUE TITLE
China cannot access google

### ISSUE THREAD

**Issue by EagleEatApple** [PredixDev/local-setup#3]
Hi,

In setup-windows.bat you're using below code to check internet connection,
ECHO Checking internet connection...
@powershell -Command "(new-object net.webclient).DownloadString('http://www.google.com')" >$null 2>&1
However, www.google.com are blocked in China, a better way is to use https://github.com.

Thanks,
Eagle

**Comment by turnerth** [comment]
Hi.  Good to know, we made the update and will put out a release soon.  Sorry for the late response.  I was in Shanghai around that time and missed this.   So, I know what you mean about the google.
